* Personal spacemacs configuration
  
Hacking Emacs!

** Dependents
- MacOS 10.14+
- Emacs 26.2+

** Installation

*** font
#+begin_src bash
brew tap homebrew/cask-fonts && brew cask install font-source-code-pro
#+end_src
*** formatters && linters
#+begin_src bash
npm install -g js-beautify typescript typescript-language-server tslint eslint
#+end_src


* FAQ 
** Why tramp hangs when spacemacs starts up?
After I tried tramp for ssh connecting remote server, spacemacs hangs with error `Tramp: Waiting for prompts from remote shell` each time I start it up.
*** Remote sever use zsh 
https://www.emacswiki.org/emacs/TrampMode#toc9
Maybe zsh of remote server is the root problem.
*** Helm using Tramp which tries to figure out some SSH/DNS settings at startup
https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-is-spacemacs-hanging-on-startup

I have tried to add these settings to `user-init`, but it didn't work.
#+begin_src elisp
(setq tramp-ssh-controlmaster-options
      "-o ControlMaster=auto -o ControlPath='tramp.%%C' -o ControlPersist=no")
#+end_src

Editing `~/.ssh/config`, no effect either.
#+begin_src
Host *
ControlMaster auto
ControlPath ~/.ssh/master -%r@%h:%p
ControlPersist = no
#+end_src

*** recentf
Try `M-x recentf-edit-list` to remove ssh files from the list. Fix it!

** How to set up Node.js autocompletion?
Does it work after applying the steps of tern's documents? If not, give lsp-mode a try.
