* Personal spacemacs configuration
  
Happy hacking!

* Table of Contents
- [[#setup][Setup]]
  - [[#dependencies][Dependencies]]
  - [[#installation][Installation]]
- [[#faq][FAQ]]
  - [[#why-tramp-hangs-when-spacemacs-starts-up][Why tramp hangs when spacemacs starts up?]]
  - [[#how-to-set-up-nodejs-autocompletion][How to set up Node.js autocompletion?]]
  - [[#why-js2-mode-always-warning-missing--after-statement][Why js2-mode always warning =missing ; after statement=?]]

* Setup
** Dependencies
- MacOS 10.14+
- Emacs 26.2+

** Installation

*** font
    
#+begin_src bash
  brew tap homebrew/cask-fonts && brew cask install font-source-code-pro
#+end_src
*** Node.js
**** formatters && linters
#+begin_src bash
  npm install -g js-beautify typescript typescript-language-server tslint eslint
#+end_src
*** C-C++
**** backend
#+begin_src bash
  brew install ccls
#+end_src

* FAQ 
** Why tramp hangs when spacemacs starts up?
After I tried tramp for ssh connecting remote server, spacemacs hangs with error =Tramp: Waiting for prompts from remote shell= each time I start it up.
*** Remote sever is using zsh 
https://www.emacswiki.org/emacs/TrampMode#toc9
Maybe zsh of remote server is the root problem.
*** Helm using Tramp which tries to figure out some SSH/DNS settings at startup
https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-is-spacemacs-hanging-on-startup

I have tried to add these settings to =user-init=, but it didn't work.
#+begin_src elisp
(setq tramp-ssh-controlmaster-options
      "-o ControlMaster=auto -o ControlPath='tramp.%%C' -o ControlPersist=no")
#+end_src

Editing =~/.ssh/config=, no effect either.
#+begin_src
Host *
ControlMaster auto
ControlPath ~/.ssh/master -%r@%h:%p
ControlPersist = no
#+end_src

*** recentf
Try =M-x recentf-edit-list= to remove ssh files from the list. Fix it!
Further more, clear all the records of this ssh connection from files in =.emacs.d/.cache/= —— =tramp=, =savehist=, =recentf= etc.
** How to set up Node.js autocompletion?
Does it work after applying the steps of tern's documents? If not, give lsp-mode a try.
** Why js2-mode always warning "missing ; after statement"?
Reference from [[https://emacs.stackexchange.com/questions/26949/can-i-turn-off-or-switch-the-syntax-checker-for-js2-mode][lunaryorn's answer]]:

The warning comes from JS2 Mode which implements its own parser for Javascript and warns about a couple of issues.
As noted in the other answer the particular warning you observed is controlled by the user option =js2-strict-missing-semi-warning= which you can set to nil in your init file or via M-x customize so as to turn off the warning.

When using JS2 Mode together with Flycheck we generally recommend to turn off all warnings of JS2 Mode by setting the variables =js2-mode-show-parse-errors= and =js2-mode-show-strict-warnings= to nil as in almost all cases Flycheck's syntax checking provides superior error reporting.


